ALTER TABLE goods
    ADD COLUMN IF NOT EXISTS condition_level VARCHAR(32) NOT NULL DEFAULT '九成新' AFTER price,
    ADD COLUMN IF NOT EXISTS contact_info VARCHAR(64) NOT NULL DEFAULT '' AFTER condition_level,
    ADD COLUMN IF NOT EXISTS cover_image_url VARCHAR(255) NULL AFTER contact_info;

ALTER TABLE goods
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'ON_SHELF';

