ALTER TABLE user
    ADD COLUMN IF NOT EXISTS audit_status VARCHAR(32) NOT NULL DEFAULT 'APPROVED' AFTER status,
    ADD COLUMN IF NOT EXISTS audit_note VARCHAR(255) NULL AFTER audit_status,
    ADD COLUMN IF NOT EXISTS audit_time DATETIME NULL AFTER audit_note;
